[build]
builder = "DOCKERFILE"
dockerfilePath = "/Dockerfile"
watchPatterns = ["client/**"]

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
