import "~/styles/globals.css";

import { type Metadata } from "next";
import {cn} from "../lib/utils";
import { Nunito, Geist_Mono } from "next/font/google";
import { Providers } from "../components/providers";
import { Toaster } from "sonner";
import { TooltipProvider } from "../components/ui/tooltip";

const fontSans = Nunito({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};



export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={cn(fontSans.variable)}>
      <body>
        <TooltipProvider>
          <Providers>{children}</Providers>
        </TooltipProvider>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
